//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pvlibrary.Model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int bid_id { get; set; }
        public int book_id { get; set; }
        public int bid_amount { get; set; }
        public decimal bid_payment { get; set; }
        public int bill_id { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Book Book { get; set; }
    }
}
